### PR TITLE
Add ESLint & Prettier config

### PR DESCRIPTION
**Pull request by avatarneil**
Supplants #105, to try and avoid merge conflicts 🙏

### CODE REVIEW

**Comment by avatarneil** [comment]
My fork must've gotten out of sync, ugh. Will try again.

**Comment by kelvinfan001** [comment]
Have you tried
```
git fetch upstream
git rebase upstream/master
git push -f
```
or were the conflicts during the `git rebase upstream/master` step already too overwhelming (this might be the case if `origin/master` hasn't been rebased against `upstream/master` in a while and the current branch was checked out from the out-of-date `origin/master`)? 

I did also commit the mortal sin of force-pushing to master last night so maybe that was it.

**Comment by kelvinfan001** [comment]
@avatarneil I may be wrong (wasn't able to clone your PR), but it doesn't look like commit [`8ab0cd9e56`](https://github.com/kelvinfan001/findalicious/pull/109/commits/8ab0cd9e5649341516bb68459ac03eb48e33aaf4) should have many conflicts with the current master; hopefully the fix was as simple as cherry-picking this one commit :)

**Comment by avatarneil** [comment]
@kelvinfan001 Ahh, yes, the force-push to master is probably what horked stuff. My fork's master is totally out of wack, and rebasing the upstream on top of it still elicits weirdness. I'll probably just re-fork and cherry-pick there. You're correct, there _shouldn't_ be that many conflicts (if any), but git is rather confused :P

**Comment by kelvinfan001** [comment]
@avatarneil Sincere apologies for the force-push (will definitely NOT do that again). Unfortunately, this might also mean your other PR may be borked 😱. I'm really hoping cherry-picking goes smoothly for the changes in the [Add Unit Settings PR](https://github.com/kelvinfan001/findalicious/pull/106). Anyways, this is a textbook example of why force-pushing to a branch that is used by others is a HORRIBLE IDEA. 

Edit: `master` is now protected from force-pushing :)

**Pull request closed without merging**
